### ISSUE TITLE
Slide sorting

### ISSUE THREAD

**Issue by angrystatic** [kookma/TW-Tamasha#18]
How does one arrange their slides. It appears to default to an order based on timestamps for the individual tiddlers or alphabetically/numerically after a refresh. What's the ideal way for users to set up their preferred order of slides?

**Comment by kookma** [comment]
Hi @angrystatic 
If you note each presentation is created by calling the macro `presenter `.

Example


```
<<presenter tag:"intro" animation:slidedown>>
```

Above example uses `intro `tag to create the presentation. That means all tiddlers with `intro `tag will be slides in the above presentation!

- Simply open one of the slides (tiddlers) tagged with `intro`
- Click on the tag pill
- In the drop down menu change the order of slides using drag and drop


**Summary**: Current release of Tamasha uses a very basic method for changing the order of slides. It uses the tag! So you can use the tag pill and reorder as you like.

**Comment by kookma** [comment]
Great you like it!
