### ISSUE TITLE
how to order slides

### ISSUE THREAD

**Issue by aalberici** [kookma/TW-Tamasha#21]
hello !
very interesting and useful plugin...
one question, i didnt find in the docs how to order slides, can you help me?

**Comment by saqimtiaz** [comment]
If you are using the tag "mytag" to create your slideshow, then re-ordering the tiddlers for that tag will re-order the slideshow.

To re-order the tiddlers for a given tag, in the sidebar click on the "More" tab, and then the "Tags" tab, click the button for "mytag" and drag and drop to re-order.

Alternatively, just type in any tiddler `<<tag mytag>>` to create a tag pill for your tag, which you can click and drag and drop to re-order.

**Comment by aalberici** [comment]
thanks Saq!

@kookma i would add this pill to the documentation of Tamasha, just for the un-initiated of TW that would benefit from the standard mechanism

**Comment by kookma** [comment]
Thank you Saq!
Hi aalberci! okay I will add Saq answer to Tamsha documentation!

**Comment by linonetwo** [comment]
Oh, this should have been in an obvious place of document! I searched for "sort" in the doc but not found, then I have to add list-after in each slide...

**Comment by kookma** [comment]
I have to update docs! Hopefully this weekend!
