### ISSUE TITLE
Is there a way to re-order the slides?

### ISSUE THREAD

**Issue by ahanniga** [kookma/TW-Tamasha#22]
I have created a presentation with around 10 slides and needed to re-order them. Is there an in-built way of doing this? I managed to find a workaround, changing `$:/plugins/kookma/tamasha/ui/slidelist` on line 10:

```xml
<$list filter="[<stateListboxTid>get[text]match[slideList]nsort[slide]]" variable="null">
```

Where the field "slide" has a numeric value.

Thanks for a great plugin!

**Comment by saqimtiaz** [comment]
See https://github.com/kookma/TW-Tamasha/issues/21

**Comment by ahanniga** [comment]
Brilliant - thanks
