### ISSUE TITLE
Assign Esc shortcut key to exit the presentation mode

### ISSUE THREAD

**Issue by kookma** [kookma/TW-Tamasha#5]
Hi @BurningTreeC - I use the keyboard shortcuts to navigate through slides and toggle presentation/author mode. Please see
https://kookma.github.io/TW-Tamasha/#%24%3A%2Fplugins%2Fkookma%2Ftamasha%2Fmacros%2Fpresenter

See below lines

```
<$keyboard key="F" actions=<<toggle-presentation-mode>> >
<$keyboard key="Q" actions=<<toggle-author-mode>> >
<$keyboard key="right down enter space" actions=<<nextSlide>> >
<$keyboard key="left up backspace"  actions=<<previousSlide>> >

```

My question is how can I use the reserved key `Esc` to exit the presentation mode! It seems I cannot assign `Esc` as the browser (here Edge, Chrome, Firefox)  uses it to exit its own full screen mode. I appreciate to advise me how can I use `Esc` key.

I see some apps have overwritten this and use `Esc` shortcut for their own use see for example https://revealjs.com/auto-slide/ on the slide press F and then Esc.

**Comment by saqimtiaz** [comment]
`<$keyboard key="escape" actions=<<myactions>> >`

**Comment by kookma** [comment]
@saqimtiaz Wonderful! 
Thanks a million!
